image: ruby:2.3

variables:
    JEKYLL_ENV: production
    GIT_SUBMODULE_STRATEGY: recursive


pages:
    except:
    - schedules
    stage: deploy
    script:
    - bundle exec jekyll build -d public
    artifacts:
        paths:
        - public
    only:
    - master
