image: ruby:2.3

variables:
    JEKYLL_ENV: production
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get -qq update && apt-get -qq install -y tor netcat-openbsd openssh-server openssh-client
    - bundle install
    - git submodule sync --recursive
    - git submodule foreach git pull origin master

pages:
    except:
    - schedules
    stage: deploy
    script:
    - bundle exec jekyll build -d public
    artifacts:
        paths:
        - public
    only:
    - master
